
#server
#port=8083
#spring.application.name = api-gateway
#eureka.client.service-url.defaultZone = http://localhost:8761/eureka/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8182/realms/roseservices
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/customer/**
        - id: fraud
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/fraud-check/**
        - id: notification
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/notification/**

        - id: order-service
          uri: http://localhost:8180
          predicates:
            - Path=/api/order

        - id: product-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/products

        - id: inventory-service
          uri: http://localhost:8181
          predicates:
            - Path=/api/inventory





