
#server
#port=8083
#spring.application.name = api-gateway
#eureka.client.service-url.defaultZone = http://localhost:8761/eureka/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/customer/**
        - id: fraud
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/fraud-check/**
        - id: notification
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/notification/**
